CREATE TABLE "restaurants" (
	"id" serial PRIMARY KEY NOT NULL,
	"owner_id" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"description" text,
	"logo" varchar(255),
	"cover_image" varchar(255),
	"phone" varchar(20),
	"email" varchar(255),
	"address" text NOT NULL,
	"city" varchar(100) NOT NULL,
	"state" varchar(100),
	"country" varchar(100),
	"zipcode" varchar(20),
	"area" varchar(100),
	"latitude" numeric(10, 7),
	"longitude" numeric(10, 7),
	"cuisine" varchar(255),
	"delivery_time" varchar(100),
	"is_open" boolean DEFAULT true,
	"is_active" boolean DEFAULT true,
	"delivery_fee" numeric(10, 2) DEFAULT '0',
	"min_order_amount" numeric(10, 2) DEFAULT '0',
	"rating" numeric(3, 2) DEFAULT '0',
	"total_reviews" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "restaurants_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "restaurants" ADD CONSTRAINT "restaurants_owner_id_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;